package com.yrdomain.classtest;
// 작성자: 김동일
// 파일:EnumJoinMember.java
public enum EnumJoinMember {
	JOINMEMBER_SUCCEED,
	JOINMEMBER_FAILED,
	LOGIN_SUCCEED,
	LOGIN_FAILED,
	WITHDRAW_SUCCED,
	WITHDRAW_FAILED,
	// 정규식 성공 시작
	REGULAR_SUCCEED_START,
	REGULAR_LASTNAME_SUCCED,
	REGULAR_FIRSTNAME_SUCCED,
	REGULAR_EMAILID_SUCCED,
	REGULAR_PW_SUCCED,
	REGULAR_PHONENUMBER_SUCCED,
	REGULAR_SUCCEED,
	REGULAR_SUCCEED_END,
	// 정규식 성공 끝
	// 정규식 실패 시작
	REGULAR_FAILED_START,
	REGULAR_LASTNAME_FAILED,
	REGULAR_FIRSTNAME_FAILED,
	REGULAR_EMAILID_FAILED,
	REGULAR_PW_FAILED,
	REGULAR_PHONENUMBER_FAILED,
	REGULAR_FAILED,
	REGULAR_FAILED_END,
	// 정규식 실패 끝
	// 검색 성공 시작
	FIND_SUCCED_START,
	FIND_LASTNAME_SUCCED,
	FIND_FIRSTNAME_SUCCED,
	FIND_EMAILID_SUCCED,
	FIND_PW_SUCCED,
	FIND_PHONENUMBER_SUCCED,
	FIND_SUCCED,
	FIND_SUCCED_END,
	// 검색 성공 끝
	// 검색 실패 시작
	FIND_FAILED_START,
	FIND_LASTNAME_FAILED,
	FIND_FIRSTNAME_FAILED,
	FIND_EMAILID_FAILED,
	FIND_PW_FAILED,
	FIND_PHONENUMBER_FAILED,
	FIND_FAILED,
	FIND_FAILED_END,
	// 검색 실패 끝
	// check 성공 시작
	CHECK_SUCCED_START,
	CHECK_LASTNAME_SUCCED,
	CHECK_FIRSTNAME_SUCCED,
	CHECK_EMAILID_SUCCED,
	CHECK_PW_SUCCED,
	CHECK_PHONENUMBER_SUCCED,
	CHECK_SUCCED,
	CHECK_SUCCED_END,
	// check 성공 끝
	// check 실패 시작
	CHECK_FAILED_START,
	CHECK_LASTNAME_FAILED,
	CHECK_FIRSTNAME_FAILED,
	CHECK_EMAILID_FAILED,
	CHECK_PW_FAILED,
	CHECK_PHONENUMBER_FAILED,
	CHECK_FAILED,
	CHECK_FAILED_END,
	// check 실패 끝
}
